<a href="https://colab.research.google.com/github/kaeatitayauk/CE888_2020_DSS/blob/master/Lab1/Lab__1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a (4 x 2) integer array and print it's attributes

In [4]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


2.Create an array of dimension (1,10) and sort it in ascending and descending order


In [18]:
array = np.arange(10)
array_ascending = np.sort(array)
print(array_ascending )
array_descending = array_ascending[::-1]
print(array_descending)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [23]:
a = np.arange(1,10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4.Stack two arrays of any size horizontally and vertically


In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
array1 = np.concatenate((a, b), axis=0)
array2 = np.concatenate((a, b.T), axis=1)
print("vertically")
print(array1)
print("-----------------")
print("horizontally")
print(array2)

vertically
[[1 2]
 [3 4]
 [5 6]]
-----------------
horizontally
[[1 2 5]
 [3 4 6]]


5.Create two array of same size and find commom elements

In [52]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[1,3],[4,5]])
print("---- Array a ----")
print(a)
print("---- Array b ----")
print(b)
print("---- Comment Elements----")
np.intersect1d(a,b)

---- Array a ----
[[1 2]
 [3 4]]
---- Array b ----
[[1 3]
 [4 5]]
---- Comment Elements----


array([1, 3, 4])

6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [65]:
a = np.random.randint(1,100,25).reshape(5,5)
print(a)
maxValue_c = np.amax(a, axis=0)
print("--- Maximum value from each column ---")
print(maxValue_c)
minValue_c = np.amin(a, axis=0)
print("--- Minimum value from each column ---")
print(minValue_c)

maxValue_r = np.amax(a, axis=1)
print("--- Maximum value from each row ---")
print(maxValue_r)
minValue_r = np.amin(a, axis= 1)
print("--- Minimum value from each row ---")
print(minValue_r)

[[32 61 48 36 73]
 [86 59 80 39 15]
 [95 11 41 12  2]
 [82 11  3 49  7]
 [93  4 96 23 71]]
--- Maximum value from each column ---
[95 61 96 49 73]
--- Minimum value from each column ---
[32  4  3 12  2]
--- Maximum value from each row ---
[73 86 95 82 96]
--- Minimum value from each row ---
[32 15  2  3  4]


7.Create an array of size 100 and compute the mean, median, standard deviation.

In [73]:
a = np.random.randint(1,100,100).reshape(10,10)
print(a)
print("--- Mean Value ---")
MeanValue = np.mean(a)
print(MeanValue)
print("--- Median Value ---")
MedianValue = np.median(a)
print(MedianValue)
print("--- standard deviation ---")
stdValue = np.std(a)
print(stdValue)


[[35  6  4 44  3 79  4 40 22 93]
 [23 61 85 14 11 21 57 50  4 30]
 [26  2 35 90 67  5 92 40 94 57]
 [56 46 87 99 20  3 87  5 49 44]
 [90 19 14 32 17 77 51  2 36 78]
 [59 72 14 56 38 37 52 40 30  1]
 [68 38 85  3  3  5  8  9 55 84]
 [99 12 68 13 29 98 13 77 81 97]
 [56 70 26 92 54 63 36 69 30 13]
 [75 68  4  3 96  2 75 92 45 86]]
--- Mean Value ---
45.05
--- Median Value ---
42.0
--- standard deviation ---
31.415402273407228


8.Normalize a 5x5 random matrix

In [74]:
a = np.random.randint(1,20,25).reshape(5,5)
print(a)

[[18 17 15  4 14]
 [18 13  5 10 18]
 [10  2 17 19 18]
 [ 7  2 13 12  3]
 [16  6  4  2 11]]


9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?


In [106]:
a = np.arange(1,49).reshape(4,4,3)
b = np.arange(1,17).reshape(4,4)

a*b[:,:,None]

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27],
        [ 40,  44,  48]],

       [[ 65,  70,  75],
        [ 96, 102, 108],
        [133, 140, 147],
        [176, 184, 192]],

       [[225, 234, 243],
        [280, 290, 300],
        [341, 352, 363],
        [408, 420, 432]],

       [[481, 494, 507],
        [560, 574, 588],
        [645, 660, 675],
        [736, 752, 768]]])