<a href="https://colab.research.google.com/github/kaeatitayauk/CE888_2020_DSS/blob/master/Lab5/Recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

#Load the data from ``jester-data-1.csv''

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv', header=None)
df

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [0]:
arr = df.copy() 
arr = arr.drop(arr.columns[0], axis=1)

In [0]:
arr = df.values
print(arr.shape)

(24983, 101)


In [0]:
rated = np.where(arr!=99)
rated

(array([    0,     0,     0, ..., 24982, 24982, 24982]),
 array([ 0,  1,  2, ..., 70, 71, 87]))

In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1835357 (1835357,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [0]:
arr[idx[0][0], idx[1][0]]

-0.97

In [0]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=1000, alpha=0.0001):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [0]:
# caseA1: latent_factors=2, iterations=20, alpha=0.0001
sgd(iterations=20, alpha=0.0001)  # Note how the MSE decreases with the number of iterations

58.080751191983424
31.58595044008887
25.27963647291544
24.70124945150947
24.653761662715038
24.64825348560044
24.64633079267306
24.64441336959885
24.641849341877197
24.638108724360226
24.632391413473588
24.623405445787107
24.609057932863553
24.58597142382676
24.548739553086236
24.48883264230683
24.393120668911024
24.242214956286016
24.00945592746136
23.66261008844112


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.554e+01, -4.803e-02, -6.486e-01, ..., -7.598e-02, -8.285e-01,
         2.464e-01],
       [ 9.530e+01,  2.216e+00,  1.517e+00, ...,  1.979e+00,  1.101e+00,
         2.524e+00],
       [ 5.453e+01,  5.816e-01,  1.639e-01, ...,  5.069e-01, -1.724e-02,
         7.770e-01],
       ...,
       [ 3.869e+01, -3.674e-01, -6.838e-01, ..., -3.513e-01, -7.475e-01,
        -2.070e-01],
       [ 3.723e+01,  8.627e-01,  5.894e-01, ...,  7.704e-01,  4.270e-01,
         9.830e-01],
       [ 7.450e+01,  9.426e-01,  3.758e-01, ...,  8.274e-01,  1.160e-01,
         1.205e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [0]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0    ...                           100
0        (74.0, 75.53943788686308)  ...    (99.0, 0.2463570049747465)
1        (100.0, 95.2991473668757)  ...    (1.07, 2.5240033647773563)
2        (49.0, 54.53377773465861)  ...     (99.0, 0.776965271044367)
3       (48.0, 49.293191239690216)  ...    (99.0, 1.5395646071786742)
4        (91.0, 93.95254275215424)  ...     (1.6, 1.2749767804089183)
...                            ...  ...                           ...
24978  (100.0, 102.82464751624556)  ...    (7.43, 1.8571663924499615)
24979    (91.0, 85.04237732083371)  ...    (8.45, 1.5649259732175862)
24980   (39.0, 38.693582419445384)  ...  (99.0, -0.20699366254295318)
24981   (37.0, 37.232125122620786)  ...    (99.0, 0.9830205091667072)
24982    (72.0, 74.50106347892029)  ...     (99.0, 1.205363831303593)

[24983 rows x 101 columns]

In [0]:
# Calculate the performance (e.g., MSE) of the algorithm on the validation dataset
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA1=sum(error)/len(error)
print("caseA1: ",mseA1)

caseA1:  23.46451095898704


Repeat the two points above changing hyper-parameters (i.e., learning rate, number of iterations of SVD, number of latent factors, etc.) as needed to get good results (you can create multiple validation sets if you want, and run a bootstrap!)

In [0]:
# caseA2: latent_factors=2, iterations=30, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=15,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA2=sum(error)/len(error)
print("caseA2: ",mseA2)

60.08308363269507
32.04462327950698
25.47211675257234
24.70675763791263
24.625315851621966
24.605428335684888
24.592118895773186
24.58004165917319
24.56851792873112
24.557359036421065
24.546409630347622
24.535467731452762
24.524241401816106
24.512294630057138
24.4989664068679
caseA2:  40.756220788200714


In [0]:
# caseA2: latent_factors=2, iterations=30, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=30,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA2=sum(error)/len(error)
print("caseA2: ",mseA2)

60.08308363269507
32.04462327950698
25.47211675257234
24.70675763791263
24.625315851621966
24.605428335684888
24.592118895773186
24.58004165917319
24.56851792873112
24.557359036421065
24.546409630347622
24.535467731452762
24.524241401816106
24.512294630057138
24.4989664068679
24.48324740759913
24.46359301652417
24.43764329268763
24.40181216397507
24.35070535311961
24.276344051566312
24.167242293188018
24.00757271627089
23.777043350751207
23.452719716822028
23.014539127493418
22.45555268775852
21.794285823646693
21.080567721407995
20.384754755310084
caseA2:  43.994942460846055


In [0]:
# caseA3: latent_factors=2, iterations=40, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA3=sum(error)/len(error)
print("caseA3: ",mseA3)

60.08308363269507
32.04462327950698
25.47211675257234
24.70675763791263
24.625315851621966
24.605428335684888
24.592118895773186
24.58004165917319
24.56851792873112
24.557359036421065
24.546409630347622
24.535467731452762
24.524241401816106
24.512294630057138
24.4989664068679
24.48324740759913
24.46359301652417
24.43764329268763
24.40181216397507
24.35070535311961
24.276344051566312
24.167242293188018
24.00757271627089
23.777043350751207
23.452719716822028
23.014539127493418
22.45555268775852
21.794285823646693
21.080567721407995
20.384754755310084
19.771779648504907
19.277668969130296
18.90501376713214
18.635124571008845
18.443025708379164
18.30641905471917
18.208437397187435
18.1372392120148
18.084743234509684
18.0454600335474
caseA3:  41.794925595306246


In [0]:
# caseB1: latent_factors=3, iterations=20, alpha=0.0001
n_latent_factors = 3
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB1=sum(error)/len(error)
print("caseB1: ",mseB1)

52.945743551915676
31.124553515077427
26.02945728402816
24.893879005275327
24.665215064291917
24.60973994947886
24.587033497689415
24.56965764680724
24.551187573717534
24.528775650845184
24.499542941425503
24.459465684050823
24.40259672386842
24.320197133500297
24.19976881646538
24.024269766180367
23.772257970972607
23.420372676492466
22.94996489813342
22.35846426530948
21.671560416788974
20.946191615383828
20.255308268706226
19.659927998610378
19.18855502590653
18.837383012844768
18.58469177943708
18.405165395742767
18.27733844964749
18.185349729373307
18.11816540094374
18.068266435255058
18.030532671508293
18.001447984028765
17.978567582626308
17.960166863111372
17.94500964785377
17.932194026947272
17.92104879028901
17.911063093750887
caseB1:  34.06542638065412
52.905451462647875
31.14221953548958
26.031823275239883
24.887501648274934
24.656456919931188
24.60037566385978
24.577557475952307
24.560279792443076
24.542104465353344
24.520263981096516
24.492022761889704
24.4535746126051
24

In [0]:
# caseB2: latent_factors=4, iterations=30, alpha=0.0001
n_latent_factors = 4
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB2=sum(error)/len(error)
print("caseB2: ",mseB2)

48.844811971355185
30.863069492129544
26.559862565545966
25.176414747121832
24.767078555285046
24.64197581579918
24.598182876062385
24.5776120872905
24.563368599792547
24.550079673697628
24.535432142169405
24.51764194402052
24.494528559283772
24.462951953270785
24.41823010924215
24.353405419606826
24.25834259567731
24.118796199528195
23.91589969377684
23.627077456898544
23.23002257972207
22.711320136076296
22.078854336386815
21.371470427929925
20.65496954317758
20.00011758683685
19.4555052656586
19.035227825943956
18.72646893091008
18.505084286700576
18.347172116639012
18.233768943602335
18.15125093154026
18.09021995009736
18.04425996861649
18.008972323794335
17.98130899355466
17.95912907100101
17.940905845971223
17.92553241484083
caseB2:  33.00232837162642
48.85060640878989
30.85363350560991
26.555606246737987
25.171664878538362
24.76152831127929
24.635932354344707
24.591852625971583
24.571123487230015
24.556837097204692
24.543651039315527
24.52931928707761
24.512169144328823
24.49019

In [0]:
# caseB3: latent_factors=5, iterations=40, alpha=0.0001
n_latent_factors = 5
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB3=sum(error)/len(error)
print("caseB3: ",mseB3)

45.654937916680325
30.584843017506003
26.944311137953157
25.476397973657424
24.91867971112305
24.70673161804132
24.62255510314717
24.585092582420813
24.56438765075661
24.549091732861402
24.534456229391505
24.517857677044777
24.49701611407576
24.4691175417444
24.43016523481288
24.374292340380766
24.292941705991097
24.173961080792832
24.00089794902721
23.75320555597863
23.408669342965624
22.949687389821392
22.373849540358563
21.70514222554064
20.996706968153088
20.317051843747958
19.72455710945649
19.248162552434056
18.88664538163574
18.621207079837298
18.428656485628498
18.288663233954605
18.185774200298177
18.108948677211217
18.05046555419034
18.00493274794431
17.96855484313346
17.938627208045258
17.913193239512346
17.890812319972216
caseB3:  31.791567599777757
45.64942513797693
30.602993991482624
26.946290176426928
25.469506489891504
24.90776644521071
24.694017127862708
24.6089492410422
24.57090153594762
24.549622876852354
24.533579978693744
24.517850933303027
24.499591784201115
24.47